### ISSUE TITLE
UI/UX改善: ポップアップとユーザーインターフェース

### ISSUE THREAD

**Issue by Nagomin-dev** [Hondy000/x-pro-enhancer#7]
## 概要
現在のUIには改善の余地があり、より良いユーザー体験を提供できます。

## 改善点
1. **ブランディングの不一致**
   - ポップアップのタイトルが「X to Bird」のまま
   - 「X Pro Enhancer」への統一が必要

2. **プレビュー機能**
   - カスタムロゴのプレビューが小さい（48px）
   - アップロード前の確認が困難

3. **フィードバック**
   - 設定保存メッセージが3秒で消える（短い）
   - エラー時のフィードバックが不十分

4. **アクセシビリティ**
   - キーボードナビゲーション未対応
   - スクリーンリーダー対応不足

## 改善案
- [ ] ポップアップUIの再デザイン
- [ ] プレビューサイズの拡大とリアルタイムプレビュー
- [ ] フィードバックメッセージの改善
- [ ] アクセシビリティ対応（ARIA属性、キーボード操作）
- [ ] ダークモード対応
- [ ] アニメーション効果の追加

## デザイン案
```css
/* 改善されたプレビュー */
.logo-preview {
  width: 100%;
  height: 120px;
  display: flex;
  align-items: center;
  justify-content: center;
  background: var(--preview-bg);
  border-radius: 8px;
  overflow: hidden;
}

.logo-preview img {
  max-width: 100%;
  max-height: 100%;
  object-fit: contain;
}
```

## 参考
- Material Design Guidelines
- Chrome Extension UI Best Practices
